spring:
  datasource:
    username: root
    password: mylog
    url: jdbc:mysql://logicer.top:3306/logicer?allowMultiQueries=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: logicer.top
    port: 6379
    database: 0
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-wait: -1
        max-idle: 10
        min-idle: 0
  rabbitmq:
    host: logicer.top
    port: 5672
    username: logicer
    password: 19970413
    virtual-host: logicer
    listener:
      simple:
        acknowledge-mode: none
        concurrency: 1
        max-concurrency: 10
        retry:
          enabled: true
qiniu:
  accesskey: k48ML3ZoFFcGdxUcXdYXGgoSArc2yJ61xxIyANLk
  secretkey: vlI9BWwW--uqWuNbuQLQL6DHm0Vqd9uWddcHslc_
  bucketname: dylan-pic
permissionCheckGrade: 1
mail:
  host: smtp.163.com
  port: 465
  username: 15966245906@163.com
  password: IXHFBQLBKYADMPVH
